### YamlMime:ModuleUnit
uid: learn.wwl.deploy-microsoft-365-apps-for-enterprise.plan-centralized-deployment-of
title: Plan a centralized deployment of Microsoft 365 Apps for enterprise
metadata:
  title: Plan a centralized deployment of Microsoft 365 Apps for enterprise
  description: "Plan a centralized deployment of Microsoft 365 Apps for enterprise"
  ms.date: 07/02/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/5-plan-centralized-deployment-of.md)]