### YamlMime:ModuleUnit
uid: learn.wwl.manage-drivers-device-peripherals.examine-printer-configuration
title: Examine printer configuration
metadata:
  title: Examine printer configuration
  description: "Examine printer configuration"
  ms.date: 02/23/2022
  author: wwlpublish
  ms.author: brhinkel
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/4-examine-printer-configuration.md)]