### YamlMime:ModuleUnit
uid: learn.wwl.plan-your-hybrid-requirements-for-your-microsoft-365-deployment.plan-hybrid-sharepoint-environment
title: Plan a hybrid SharePoint environment
metadata:
  title: Plan a hybrid SharePoint environment
  description: "Plan a hybrid SharePoint environment"
  ms.date: 06/29/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 8
content: |
  [!include[](includes/3-plan-hybrid-sharepoint-environment.md)]