### YamlMime:ModuleUnit
uid: learn.wwl.explore-threat-protection-microsoft-365-defender.explore-using-configuration-analyzer
title: Explore using Configuration Analyzer to improve security policies
metadata:
  title: Explore using Configuration Analyzer to improve security policies
  description: "Explore using Configuration Analyzer to improve security policies"
  ms.date: 10/18/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/3-explore-using-configuration-analyzer.md)]