### YamlMime:ModuleUnit
uid: learn.wwl.configure-ip-network-connectivity.examine-tools-configuring-network-settings
title: Examine tools for configuring network settings
metadata:
  title: Examine tools for configuring network settings
  description: "Examine tools for configuring network settings"
  ms.date: 03/31/2022
  author: wwlpublish
  ms.author: brhinkel
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/7-examine-tools-configuring-network-settings.md)]