### YamlMime:ModuleUnit
uid: learn-m365-office.m365-managing-troubleshooting-office.add-apps-language-configuration
title: Add apps, languages, or configurations to existing Office installations
metadata:
  title: Add apps, languages, or configurations to existing Office installations
  description: Learn how to Add apps, languages, or configurations to existing Office installations
  ms.date: 07/14/2021
  author: puffinanda
  ms.author: v-jolev
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 2
content: |
  [!include[](includes/add-apps-language-configuration.md)]