### YamlMime:ModuleUnit
uid: learn.wwl.implement-microsoft-cloud-application-security.deploy-cloud-app-security
title: Deploy Cloud App Security
metadata:
  title: Deploy Cloud App Security
  description: "Deploy Cloud App Security"
  ms.date: 09/14/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
sandbox: false
labModal: false
durationInMinutes: 6
content: |
  [!include[](includes/3-deploy-cloud-app-security.md)]