### YamlMime:ModuleUnit
uid: learn.wwl.prepare-your-windows-10-devices-for-co-management.configure-configuration-manager
title: Configure Configuration Manager for Co-management
metadata:
  title: Configure Configuration Manager for Co-management
  description: "Configure Configuration Manager for Co-management"
  ms.date: 06/25/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 4
content: |
  [!include[](includes/3-configure-configuration-manager.md)]
quiz:
  title: "Check your knowledge"
  questions:
  - content: "When running the Co-management Configuration Wizard, the \"Automatic enrollment in Intune\" setting enables you to select whether you want to automatically enroll all devices, selected devices, or no devices that are managed by Configuration Manager in Intune. For this setting, which option enables you to enroll selected devices?"
    choices:
    - content: "Targeted devices"
      isCorrect: false
      explanation: "That's incorrect. This item isn't the option to enroll selected devices. Try again."
    - content: "Pilot"
      isCorrect: true
      explanation: "That's correct. The Pilot option should be selected to enroll selected devices."
    - content: "Limited"
      isCorrect: false
      explanation: "That's incorrect. This item isn't the option to enroll selected devices."