### YamlMime:ModuleUnit
uid: learn-m365.m365-messaging-manage-org-settings.configure-org-sharing
title: Configure organizational sharing
metadata:
  title: Configure organizational sharing
  description: Plan and manage organizational settings such as global address lists, offline address books, address policies, organizational sharing, and add-ins in Exchange Online. 
  ms.date: 07/14/2021
  author: AlexandraHrt
  ms.author: teleary
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 7
content: |
  [!include[](includes/configure-org-sharing.md)]