### YamlMime:ModuleUnit
uid: learn-m365.optimize-wvd.configure-automation
title: Automate depth and breadth scaling for Azure Virtual Desktop host pools 
metadata:
  title: Automate depth and breadth scaling for Azure Virtual Desktop host pools
  description: Learn how to configure automatic depth and breadth scaling for Azure Virtual Desktop host pools.
  ms.date: 07/14/2021
  author: lizap
  ms.author: elizapo
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 3
content: |
  [!include[](includes/5-configure-automation.md)]