### YamlMime:ModuleUnit
uid: learn.wwl.implement-azure-ad-connect.configure-prerequisites
title: Configure Azure AD Connect prerequisites
metadata:
  title: Configure Azure AD Connect prerequisites
  description: "Configure Azure AD Connect prerequisites"
  ms.date: 07/12/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 7
content: |
  [!include[](includes/2-configure-prerequisites.md)]