### YamlMime:ModuleUnit
uid: learn.wwl.manage-device-compliance.configure-conditional-users-groups
title: Configure conditional users and groups
metadata:
  title: Configure conditional users and groups
  description: "Configure conditional users and groups"
  ms.date: 09/15/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
sandbox: false
labModal: false
durationInMinutes: 4
content: |
  [!include[](includes/3-configure-conditional-users-groups.md)]