### YamlMime:ModuleUnit
uid: learn.wwl.troubleshoot-issues-signing-into-microsoft-teams.validate-network-configuration
title: Validate network configuration
metadata:
  title: Validate network configuration
  description: "Validate network configuration"
  ms.date: 08/24/2021
  author: wwlpublish
  ms.author: cyncarey
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 5
content: |
  [!include[](includes/2-validate-network-configuration.md)]