### YamlMime:ModuleUnit
uid: learn.create-device-configuration.standard-device-configuration
title: Protective device configuration
metadata:
  unitType: learning-content
  title: Protective device configuration
  description: Protective device configuration
  ms.date: 04/01/2022 
  author: Erikre 
  ms.author: erikre 
  ms.topic: interactive-tutorial 
  ms.prod: learning-endpoint-manager
durationInMinutes: 4
content: |
  [!include[](includes/4-standard-device-configuration.md)]
