### YamlMime:ModuleUnit
uid: learn.create-device-configuration.complex-device-configuration
title: Comprehensive device configuration
metadata:
  unitType: learning-content
  title: Comprehensive device configuration
  description: Comprehensive device configuration
  ms.date: 04/01/2022 
  author: Erikre 
  ms.author: erikre 
  ms.topic: interactive-tutorial 
  ms.prod: learning-endpoint-manager
durationInMinutes: 3
content: |
  [!include[](includes/5-complex-device-configuration.md)]
