### YamlMime:ModuleUnit
uid: learn-m365.msgraph-javascript-app.4-register-application
metadata:
  title: Register an application with Azure Active Directory
  description: Learn how to register your JavaScript application with Azure Active Directory.
  ms.date: 02/17/2021
  author: aycabas
  ms.author: aycabas
  ms.topic: interactive-tutorial
  ms.prod: learning-graph
  ms.custom: team=cloud_advocates
  ms.contributors: aycabas-03262021
title: Register an application with Azure Active Directory
durationInMinutes: 3
content: |
  [!include[](includes/4-register-application.md)]
