### YamlMime:ModuleUnit
uid: learn.wwl.describe-cloud-security-capabilities-of-microsoft-365.take-control-of-your-cloud-environment-with-microsoft-cloud-app-security
title: Take control of your cloud environment with Microsoft Defender for Cloud Apps
metadata:
  title: Take control of your cloud environment with Microsoft Defender for Cloud Apps
  description: "Take control of your cloud environment with Microsoft Defender for Cloud Apps"
  ms.date: 02/16/2021
  author: wwlpublish
  ms.author: ceperezb
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/2-take-control-of-cloud-environment.md)]
