### YamlMime:ModuleUnit
uid: learn.wwl.manage-your-business-with-microsoft-365.business-process-automation
title: Business process automation
metadata:
  title: Business process automation
  description: "Business process automation"
  ms.date: 10/18/2021
  author: wwlpublish
  ms.author: dahans
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 8
content: |
  [!include[](includes/4-business-process-automation.md)]