### YamlMime:ModuleUnit
uid: learn-m365.msteams-teamwork-endpoint.4-manage-configurable-tabs
metadata:
  title: Configure a built-in tab with Microsoft Graph
  description: Built-in Microsoft Teams tabs for websites, Office documents, SharePoint document libraries, and other tabs can be configured using Microsoft Graph. In this unit, you'll learn how to configure an existing built-in tab with Microsoft Graph.
  ms.date: 09/13/2021
  author: andrewconnell-msft
  ms.author: suzanz
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
title: Configure a built-in tab with Microsoft Graph
durationInMinutes: 7
content: |
  [!include[](includes/4-manage-configurable-tabs.md)]
