### YamlMime:ModuleUnit
uid: learn-m365.audit-physical-security.device-security
title: Data bearing device security
metadata:
  title: Data bearing device security
  description: Learn how Microsoft uses Defense-In-Depth to secure our datacenters against unauthorized access, environmental hazards, and other physical threats, as well as how Microsoft implements resilient architecture, business continuity, and disaster recovery to maintain the availability of our services.
  ms.date: 06/30/2020
  author: beccarobins
  ms.author: beccarobins
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 2
content: |
  [!include[](includes/device-security.md)]