### YamlMime:ModuleUnit
uid: learn.wwl.plan-configure-network-settings-for-microsoft-teams.plan-for-network-deployment-using-network-planner
title: Plan for network deployment using Network Planner
metadata:
  title: Plan for network deployment using Network Planner
  description: "Plan for network deployment using Network Planner"
  ms.date: 10/25/2021
  author: wwlpublish
  ms.author: jennyche
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/03-plan-network-deployment-using-network-planner.md)]