### YamlMime:ModuleUnit
uid: learn.wwl.implement-applications-azure-ad.add-application-within-your-tenant
title: Add an application within your Azure AD tenant
metadata:
  title: Add an application within your Azure AD tenant
  description: "Add an application within your Azure AD tenant"
  ms.date: 07/12/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 4
content: |
  [!include[](includes/2-add-application-within-your-tenant.md)]
quiz:
  title: "Check your knowledge"
  questions:
  - content: "As the Enterprise Administrator for Contoso, Holly Dickson is registering a new application using the Azure portal. When selecting the Application type, Holly selects the “Native” option. What does this option indicate?"
    choices:
    - content: "The application is a Web-based client app that is installed locally on a device"
      isCorrect: false
      explanation: "That's incorrect. This description doesn't apply to the Native option. Try again."
    - content: "The application is a Resource application that is installed on a secure server"
      isCorrect: false
      explanation: "That's incorrect. This description doesn't apply to the Native option. This description applies to the Web app/API option, which is for Web app/API client applications and resource/API applications installed on a secure server. Try again."
    - content: "The application is a Client application that is installed locally on a device"
      isCorrect: true
      explanation: "That's correct. The Native option applies to client applications that are installed locally on a device. This setting is used for OAuth public native clients."