### YamlMime:ModuleUnit
uid: learn.wwl.implement-applications-azure-ad.update-application-within-consent-framework
title: Update an application within the Azure AD consent framework
metadata:
  title: Update an application within the Azure AD consent framework
  description: "Update an application within the Azure AD consent framework"
  ms.date: 07/12/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 4
content: |
  [!include[](includes/3-update-application-within-consent-framework.md)]