### YamlMime:ModuleUnit
uid: learn.wwl.implement-applications-azure-ad.remove-applications-registration-from-your-tenant
title: Remove an application's registration from your Azure AD tenant
metadata:
  title: Remove an application's registration from your Azure AD tenant
  description: "Remove an application's registration from your Azure AD tenant"
  ms.date: 07/12/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/5-remove-applications-registration-from-your-tenant.md)]