### YamlMime:ModuleUnit
uid: learn.wwl.migrate-voice-services-from-skype-for-business-server-to-teams.implement-teams-hybrid-configuration
title: Implement Teams Hybrid Configuration
metadata:
  title: Implement Teams Hybrid Configuration
  description: "Implement Teams Hybrid Configuration"
  ms.date: 12/29/2021
  author: wwlpublish
  ms.author: dahans
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/4-implement-teams-hybrid-configuration.md)]