### YamlMime:ModuleUnit
uid: learn-m365.teams.configure-manage-direct-routing.2-configure-connect-session-border-controller
title: Configure and connect the Session Border Controller (SBC)
metadata:
  title: Configure and connect the Session Border Controller (SBC)
  description: Learn how to configure SBCs.
  ms.date: 07/16/2021
  author: temanteleary
  ms.author: teleary
  ms.topic: interactive-tutorial
  ms.prod: learning-teams
durationInMinutes: 4
content: |
  [!include[](includes/2-configure-connect-session-border-controller.md)]