### YamlMime:ModuleUnit
uid: learn-m365.information-protection-microsoft-cloud-app-security.2-connect-cloud-app-security
metadata:
  title: Connect apps to Microsoft Defender for Cloud Apps
  description: Connect apps to Microsoft Defender for Cloud Apps
  ms.date: 07/02/2021
  author: beccarobins
  ms.author: beccarobins
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
title: Connect apps to Microsoft Defender for Cloud Apps
durationInMinutes: 7
content: |
  [!include[](includes/2-connect-cloud-app-security.md)]
