### YamlMime:ModuleUnit
uid: learn-m365.m365-teams-collab-manage-meetings.meeting-conferencing-deployment
title: Plan for meeting and conferencing deployment 
metadata:
  title: Plan for meeting and conferencing deployment
  description: Learn how to plan and manage Microsoft Teams meetings and conferences. Discover how audio conferencing and live events work in Teams.
  ms.date: 07/15/2021
  author: AlexandraHrt
  ms.author: elizapo
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 4
content: |
  [!include[](includes/meeting-conferencing-deployment.md)]
