### YamlMime:ModuleUnit
uid: learn.wwl.implement-security-for-microsoft-teams.configure-safe-attachments
title: Configure Safe Attachments for Microsoft Teams
metadata:
  title: Configure Safe Attachments for Microsoft Teams
  description: "Configure Safe Attachments for Microsoft Teams"
  ms.date: 03/07/2022
  author: wwlpublish
  ms.author: jennyche
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/03-configure-safe-attachments.md)]