### YamlMime:ModuleUnit
uid: learn-m365.teams.rollout-using-advisor.3-create-deployment-plan
title: Create and manage a deployment plan
metadata:
  title: Create and manage a deployment plan
  description: Learn how to manage your deployment plan.
  ms.date: 07/15/2021
  ms.author: elizapo
  author: lizap
  ms.topic: interactive-tutorial
  ms.prod: learning-teams
durationInMinutes: 1
content: |
  [!include[](includes/3-create-deployment-plan.md)]