### YamlMime:ModuleUnit
uid: learn.wwl.assess-deployment-readiness.assess-application-compatibility
title: Assess application compatibility
metadata:
  title: Assess application compatibility
  description: "Assess application compatibility"
  ms.date: 03/17/2022
  author: wwlpublish
  ms.author: brhinkel
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/4-assess-application-compatibility.md)]