### YamlMime:ModuleUnit
uid: learn-m365.implement-mcas-cloud-discovery.2-what-is-cloud-discovery-in-cloud-app-security
metadata:
  title: What is Cloud Discovery in Defender for Cloud Apps?
  description: Use Cloud Discovery in Microsoft Defender for Cloud Apps to learn about the apps being used in your organization
  ms.date: 11/03/2021
  author: beccarobins
  ms.author: beccarobins
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
title: What is Cloud Discovery in Defender for Cloud Apps?
durationInMinutes: 9
content: |
  [!include[](includes/2-what-is-cloud-discovery-in-cloud-app-security.md)]
