### YamlMime:ModuleUnit
uid: learn-m365.m365-teams-collab-apps-bots-connectors.configure-manage-bots
title: Configure and manage bots for private chats and channels 
metadata:
  title: Configure and manage bots for private chats and channels
  description: Discover how apps, bots, and connectors increase the power of Microsoft Teams. Learn how to manage apps, bots, and connectors as you plan your organizationâ€™s Teams rollout.  
  ms.date: 07/31/2019
  author: AlexandraHrt
  ms.author: aleha
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
  ROBOTS: NOINDEX
durationInMinutes: 4
content: |
  [!include[](includes/configure-manage-bots.md)]