### YamlMime:ModuleUnit
uid: learn.wwl.implement-office-telemetry.install-configure
title: Install and configure Office Telemetry
metadata:
  title: Install and configure Office Telemetry
  description: "Install and configure Office Telemetry"
  ms.date: 07/01/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 4
content: |
  [!include[](includes/5-install-configure.md)]