### YamlMime:ModuleUnit
uid: learn.wwl.evaluate-windows-client-installation-methods.evaluate-new-deployment-options
title: Evaluate new deployment options
metadata:
  title: Evaluate new deployment options
  description: "Evaluate new deployment options"
  ms.date: 02/08/2022
  author: wwlpublish
  ms.author: brhinkel
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/5-evaluate-new-deployment-options.md)]