### YamlMime:ModuleUnit
uid: learn.wwl.explore-common-configuration-options.use-settings-app
title: Use the settings app
metadata:
  title: Use the settings app
  description: "Use the settings app"
  ms.date: 02/18/2022
  author: wwlpublish
  ms.author: brhinkel
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/4-use-settings-app.md)]