### YamlMime:ModuleUnit
uid: learn.wwl.explore-common-configuration-options.configure-power-plans
title: Configure power plans
metadata:
  title: Configure power plans
  description: "Configure power plans"
  ms.date: 02/18/2022
  author: wwlpublish
  ms.author: brhinkel
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/8-configure-power-plans.md)]