### YamlMime:ModuleUnit
uid: learn-m365.m365-teams-upgrade-plan-upgrade.verify-environment
title: Verify your environment meets all prerequisites and dependencies for Teams
metadata:
  title: Verify your environment meets all prerequisites and dependencies for Teams
  description: Learn about the environmental dependencies needed when upgrading to Microsoft Teams.
  ms.date: 07/15/2021
  author: AlexandraHrt
  ms.author: elizapo
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 1
content: |
  [!include[](includes/verify-environment.md)]