### YamlMime:ModuleUnit
uid: learn.wwl.examine-windows-10-deployment-scenarios.examine-modern-deployment-methods
title: Examine the modern deployment methods
metadata:
  title: Examine the modern deployment methods
  description: "Examine the modern deployment methods"
  ms.date: 06/25/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/4-examine-modern-deployment-methods.md)]