### YamlMime:ModuleUnit
uid: learn.wwl.examine-windows-10-deployment-scenarios.examine-traditional-deployment-methods
title: Examine the traditional deployment methods
metadata:
  title: Examine the traditional deployment methods
  description: "Examine the traditional deployment methods"
  ms.date: 06/25/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/6-examine-traditional-deployment-methods.md)]