### YamlMime:ModuleUnit
uid: learn-m365.teams.navigate-admin-portal.2-configure-your-teams-development
title: Configure your Teams deployment
metadata:
  title: Configure your Teams deployment
  description: Learn about the core decisions you need to take as you deploy and configure Teams.
  ms.date: 07/16/2021
  ms.author: teleary
  author: lizap
  ms.topic: interactive-tutorial
  ms.prod: learning-teams
durationInMinutes: 7
content: |
  [!include[](includes/2-configure-your-teams-development.md)]