### YamlMime:ModuleUnit
uid: learn.wwl.manage-microsoft-defender-windows-client.explore-windows-defender-firewall-advanced-security
title: Explore Windows Defender Firewall with Advanced Security
metadata:
  title: Explore Windows Defender Firewall with Advanced Security
  description: "Explore Windows Defender Firewall with Advanced Security"
  ms.date: 03/31/2022
  author: wwlpublish
  ms.author: brhinkel
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 4
content: |
  [!include[](includes/6-explore-windows-defender-firewall-advanced-security.md)]