### YamlMime:ModuleUnit
uid: learn.wwl.deploy-mobile-device-management.configure-domains-for-mobile-device-management
title: Configure domains for Mobile Device Management
metadata:
  title: Configure domains for Mobile Device Management
  description: "Configure domains for Mobile Device Management"
  ms.date: 07/27/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/3-configure-domains-for-mobile-device-management.md)]