### YamlMime:ModuleUnit
uid: learn-m365.compliance-discover-advanced-audit.configure
title: Configure audit log settings
metadata:
  title: Configure audit log settings
  description: Microsoft 365 delivers comprehensive audit logs and alerts across more than 15 services, which enables customers to track user and administration activity within their tenants. Improvements in Advanced Auditing in Microsoft 365 include preservation of audit logs for up to a year, faster access to data, and access to crucial events for quicker investigations.
  ms.date: 08/04/2021
  author: ericweisberg
  ms.author: beccarobins
  ms.topic: interactive-tutorial
  ms.prod: learning-m365

durationInMinutes: 3
content: |
  [!include[](includes/configure.md)]