### YamlMime:ModuleUnit
uid: learn.wwl.manage-virtual-desktops.configure-windows-365
title: Configure Windows 365
metadata:
  title: Configure Windows 365
  description: "Configure Windows 365"
  ms.date: 03/24/2022
  author: wwlpublish
  ms.author: brhinkel
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 4
content: |
  [!include[](includes/4-configure-windows-365.md)]