### YamlMime:ModuleUnit
uid: learn-m365.teams.migrate-direct-routing.4-configure-dynamic-routing
title: Configure dynamic routing
metadata:
  title: Configure dynamic routing
  description: See what dynamic routing looks like, how to configure an LDAP connection, and see an example of how to configure a specific SBC.
  ms.date: 09/15/2020
  author: temanteleary
  ms.author: teleary
  ms.topic: interactive-tutorial
  ms.prod: learning-teams
durationInMinutes: 6
content: |
  [!include[](includes/4-configure-dynamic-routing.md)]