### YamlMime:ModuleUnit
uid: learn.wwl.explore-messaging-compliance-exchange.configure-messaging-records-management
title: Configure Messaging Records Management
metadata:
  title: Configure Messaging Records Management
  description: "Configure Messaging Records Management"
  ms.date: 11/01/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 9
content: |
  [!include[](includes/3-configure-messaging-records-management.md)]