### YamlMime:ModuleUnit
uid: learn.wwl.configure-organizational-settings.configure-quota-configurations
title: Configure quota configurations
metadata:
  title: Configure quota configurations
  description: "Configure quota configurations"
  ms.date: 12/22/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 4
content: |
  [!include[](includes/3-configure-quota-configurations.md)]