### YamlMime:ModuleUnit
uid: learn.wwl.configure-troubleshoot-microsoft-teams-clients-services.configure-troubleshoot-audio-conferencing
title: Configure and troubleshoot audio conferencing
metadata:
  title: Configure and troubleshoot audio conferencing
  description: "Configure and troubleshoot audio conferencing"
  ms.date: 08/24/2021
  author: wwlpublish
  ms.author: cyncarey
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 8
content: |
  [!include[](includes/6-configure-troubleshoot-audio-conferencing.md)]