### YamlMime:ModuleUnit
uid: learn-wwl.manage-applications-by-using-microsoft-intune.4-administering-applications
title: Administering applications
metadata:
  title: Administering applications
  description: Learn about the steps involved to deploy apps using Microsoft Intune.
  ms.date: 07/15/2021
  author: temanteleary
  ms.author: teleary
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 4
content: |
  [!include[](includes/4-administering-applications.md)] 