### YamlMime:ModuleUnit
uid: learn.wwl.simplify-device-management-with-microsoft-endpoint-manager.configuration-manager
title: Configuration Manager
metadata:
  title: Configuration Manager
  description: "Configuration Manager"
  ms.date: 08/31/2021
  author: wwlpublish
  ms.author: dahans
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/5-configuration-manager.md)]