### YamlMime:ModuleUnit
uid: learn.wwl.simplify-device-management-with-microsoft-endpoint-manager.autopilot-zero-touch-deployment
title: AutoPilot and zero-touch deployment
metadata:
  title: AutoPilot and zero-touch deployment
  description: "AutoPilot and zero-touch deployment"
  ms.date: 08/11/2021
  author: wwlpublish
  ms.author: dahans
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/6-autopilot-zero-touch-deployment.md)]