### YamlMime:ModuleUnit
uid: learn-m365.audit-security-development-operation.open-source-security
title: Understand open source security at Microsoft
metadata:
  title: Understand open source security at Microsoft
  description: Learn how Microsoft 365 follows Microsoftâ€™s Security Development Lifecycle (SDL) to build security and privacy into our products and services.
  ms.date: 05/29/2020
  author: NamrahK
  ms.author: v-nakhu
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 2
content: |
  [!include[](includes/open-source-security.md)]