### YamlMime:ModuleUnit
uid: learn.wwl.plan-your-premises-infrastructure-for-microsoft-365.manage-your-transition-to-by-using-deployment-planning-checklist
title: Manage your transition to Microsoft 365 by using the Deployment Planning Checklist
metadata:
  title: Manage your transition to Microsoft 365 by using the Deployment Planning Checklist
  description: "Manage your transition to Microsoft 365 by using the Deployment Planning Checklist"
  ms.date: 06/30/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 5
content: |
  [!include[](includes/3-manage-your-transition-to-by-using-deployment-planning-checklist.md)]
quiz:
  title: "Check your knowledge"
  questions:
  - content: "As Fabrikam's Enterprise Administrator, you're using Microsoft's Deployment Planning Checklist to help keep your Microsoft 365 deployment on schedule. You have determined your deployment goals and inventoried your current environment. Which of the following tasks should you do next?"
    choices:
    - content: "Collect details about any intranet sites that you plan to migrate"
      isCorrect: false
      explanation: "That's incorrect. This task would be performed when you inventory your current environment. Try again."
    - content: "Prepare for directory synchronization"
      isCorrect: false
      explanation: "That's incorrect. This task would be performed when you set up Microsoft 365 services to work for your organization. Try again."
    - content: "Update client software versions"
      isCorrect: true
      explanation: "That's correct. After determining your deployment goals and taking inventory of your current environment, the next step in the Deployment Planning Checklist is to fix potential deployment blockers. Updating client software versions is one of the tasks that should be completed within this step."