### YamlMime:ModuleUnit
uid: learn-m365.configure-microsoft-cloud-app-security-initial-settings.2-configure-ip-address-ranges
metadata:
  title: Configure IP address ranges
  description: Learn to configure IP address ranges in Cloud App Security.
  ms.date: 07/20/2021
  author: geoffallix
  ms.author: beccarobins
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
title: Configure IP address ranges
durationInMinutes: 6
content: |
  [!include[](includes/2-configure-ip-address-ranges.md)]
