### YamlMime:ModuleUnit
uid: learn-m365.m365-messaging-configure-transport-architecture.configure-connectors
title: Create and configure connectors to route email
metadata:
  title: Create and configure connectors to route email on-premises
  description: Create connectors to use to route email to on-premises email systems. 
  ms.date: 06/04/2029
  author: AlexandraHrt
  ms.author: v-aleha
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 3
content: |
  [!include[](includes/configure-connectors.md)]