### YamlMime:ModuleUnit
uid: learn.wwl.implement-windows-autopilot.examine-pre-provisioned-deployment-model
title: Examine the Windows Autopilot pre-provisioned deployment model
metadata:
  title: Examine the Windows Autopilot pre-provisioned deployment model
  description: "Examine the Windows Autopilot pre-provisioned deployment model"
  ms.date: 06/30/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 5
content: |
  [!include[](includes/6-examine-pre-provisioned-deployment-model.md)]