### YamlMime:ModuleUnit
uid: learn.wwl.introduction-to-privileged-identity-management.configure
title: Configure Privileged Identity Management
metadata:
  title: Configure Privileged Identity Management
  description: "Configure Privileged Identity Management"
  ms.date: 04/28/2022
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 5
content: |
  [!include[](includes/3-configure.md)]
quiz:
  title: "Check your knowledge"
  questions:
  - content: "As Fabrikam's Enterprise Administrator, Holly Spencer wants to implement Privileged Identity Management. Holly has discovered and selected the Fabrikam resources to protect with Privileged Identity Management. What is the next step that Holly should complete in the PIM setup process?"
    choices:
    - content: "Elevate access for a Global Administrator"
      isCorrect: false
      explanation: "Incorrect. This action is the final step in the setup process."
    - content: "Assign other users to the Privileged Role Administrator role"
      isCorrect: true
      explanation: "Correct. To delegate access to PIM, a Global Administrator can assign other users to the Privileged Role Administrator role. By default, Security administrators and Security readers have read-only access to Privileged Identity Management. To grant access to Privileged Identity Management, the first user can assign others to the Privileged Role Administrator role."
    - content: "Respond to user requests for a role"
      isCorrect: false
      explanation: "Incorrect. This action is one of the ongoing tasks for a Privileged Role Admin once PIM is set up."