### YamlMime:ModuleUnit
uid: learn.wwl.get-done-stay-secure-with-windows-10.deployment-methods
title: Explore deployment methods for Windows 10
metadata:
  title: Explore deployment methods for Windows 10
  description: "Explore deployment methods for Windows 10"
  ms.date: 10/19/2021
  author: wwlpublish
  ms.author: dahans
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/3-deployment-methods.md)]