### YamlMime:ModuleUnit
uid: learn.wwl.manage-microsoft-defender-endpoint.explore-microsoft-defender-application-guard
title: Explore Microsoft Defender Application Guard
metadata:
  title: Explore Microsoft Defender Application Guard
  description: "Explore Microsoft Defender Application Guard"
  ms.date: 03/31/2022
  author: wwlpublish
  ms.author: brhinkel
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 3
content: |
  [!include[](includes/5-explore-microsoft-defender-application-guard.md)]