### YamlMime:ModuleUnit
uid: learn.wwl.configure-client-aconnectivity-to-microsoft-365.examine-how-automatic-client-configuration-works
title: Examine how automatic client configuration works
metadata:
  title: Examine how automatic client configuration works
  description: "Examine how automatic client configuration works"
  ms.date: 03/30/2022
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 2
content: |
  [!include[](includes/2-examine-how-automatic-client-configuration-works.md)]