### YamlMime:ModuleUnit
uid: learn.wwl.configure-client-aconnectivity-to-microsoft-365.configure-outlook-clients
title: Configure Outlook clients
metadata:
  title: Configure Outlook clients
  description: "Configure Outlook clients"
  ms.date: 07/01/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 5
content: |
  [!include[](includes/4-configure-outlook-clients.md)]
quiz:
  title: "Check your knowledge"
  questions:
  - content: "Microsoft 365 clients can connect to services such as Exchange Online and SharePoint Online. Each service contains a feature that clients use to make these connections. Which of the following features is it that enables these connections?"
    choices:
    - content: "fully qualified domain names (FQDNs)"
      isCorrect: false
      explanation: "That's incorrect. Clients don't use this feature to connect to services such as Exchange Online and SharePoint Online. Try again."
    - content: "Microsoft 365 endpoints"
      isCorrect: true
      explanation: "That's correct. Microsoft 365 services contain multiple endpoints, through which clients connect to services such as Exchange Online and SharePoint Online. IPv4 and IPv6 address ranges and fully qualified domain names (FQDNs) are properties included in each endpoint (including ports, URLs, and IPv4 and IPv6 address ranges). However, it's the endpoints themselves that clients use to connect to services such as Exchange Online and SharePoint Online."
    - content: "IPv4 and IPv6 address ranges"
      isCorrect: false
      explanation: "That's incorrect. Clients don't use this feature to connect to services such as Exchange Online and SharePoint Online. Try again."