### YamlMime:ModuleUnit
uid: learn.wwl.configure-client-aconnectivity-to-microsoft-365.configure-azure-active-directory-multifactor-authentication
title: Configure Azure Active Directory multifactor authentication
metadata:
  title: Configure Azure Active Directory multifactor authentication
  description: "Configure Azure Active Directory multifactor authentication"
  ms.date: 07/01/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/5-configure-azure-active-directory-multifactor-authentication.md)]