### YamlMime:ModuleUnit
uid: learn-wwl.deploy-windows-update-in-microsoft-365.4-using-group-policy-configure-windows-update
title: Using Group Policy to configure Windows Update
metadata:
  title: Using Group Policy to configure Windows Update
  description: Display how to configure Group Policy to manage Windows Update.
  ms.date: 09/09/2021
  author: beccarobins
  ms.author: beccarobins
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 4
content: |
  [!include[](includes/4-using-group-policy-configure-windows-update.md)] 