### YamlMime:ModuleUnit
uid: learn-m365.m365-compliance-information-govern-information.configure-retention-policies
title: Configure retention policies
metadata:
  title: Configure retention policies
  description: Learn how to manage your content lifecycle using solutions to import, store, and classify business-critical data so you can keep what you need and delete what you don't. 
  ms.date: 10/28/2021
  author: beccarobins
  ms.author: beccarobins
  ms.topic: interactive-tutorial
  ms.prod: learning-m365

durationInMinutes: 15
content: |
  [!include[](includes/configure-retention-policies.md)]