### YamlMime:ModuleUnit
uid: learn-m365.m365-compliance-information-govern-information.configure-auto-apply-retention-policies
title: Configure auto-apply retention label policies
metadata:
  title: Configure auto-apply retention label policies
  description: Learn how to manage your content lifecycle using solutions to import, store, and classify business-critical data so you can keep what you need and delete what you don't. 
  ms.date: 07/07/2021
  author: beccarobins
  ms.author: beccarobins
  ms.topic: interactive-tutorial
  ms.prod: learning-m365

durationInMinutes: 8
content: |
  [!include[](includes/configure-auto-apply-retention-policies.md)]