### YamlMime:ModuleUnit
uid: learn.wwl.configure-teams-phone-system.manage-configure-microsoft-phone-numbers
title: Manage and configure Microsoft PSTN numbers
metadata:
  title: Manage and configure Microsoft PSTN numbers
  description: "Manage and configure Microsoft PSTN numbers"
  ms.date: 11/08/2021
  author: wwlpublish
  ms.author: dahans
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 14
content: |
  [!include[](includes/3-manage-configure-microsoft-phone-numbers.md)]