### YamlMime:ModuleUnit
uid: learn.wwl.explore-microsoft-search-user-experience.configure
title: Configure Microsoft Search
metadata:
  title: Configure Microsoft Search
  description: "Configure Microsoft Search"
  ms.date: 06/14/2020
  author: wwlpublish
  ms.author: ceperezb
  ms.topic: interactive-tutorial
  ms.prod: learning-windows
azureSandbox: false
durationInMinutes: 9
content: |
  [!include[](includes/4-configure.md)]