### YamlMime:ModuleUnit
uid: learn-m365.teams.manage-calls-using-auto-attendants.4-configure-use-auto-attendants
title: Configure and use auto attendants
metadata:
  title: Configure and use auto attendants
  description: Learn how to set up extension dialing and shared mailboxes in Microsoft Teams.
  ms.date: 07/16/2021
  ms.author: teleary
  author: temanteleary
  ms.topic: interactive-tutorial
  ms.prod: learning-teams
durationInMinutes: 2
content: |
  [!include[](includes/4-configure-use-auto-attendants.md)]