### YamlMime:ModuleUnit
uid: learn-m365.identity-application-types.2-single-page-applications
metadata:
  title: Single-page applications
  description: In this unit, youâ€™ll learn how to create, configure, and use Azure AD applications that use data returned from Microsoft Graph in single-page applications by using the OAuth 2.0 implicit grant flow.
  ms.date: 08/17/2020
  author: andrewconnell
  ms.author: v-johnco
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
title: Single-page applications
durationInMinutes: 1
content: |
  [!include[](includes/2-single-page-applications.md)]
