### YamlMime:ModuleUnit
uid: learn-m365.identity-application-types.3-exercise-single-page-applications
metadata:
  title: Exercise - Single-page applications
  description: In this exercise, youâ€™ll learn how to create, configure, and use Azure AD applications that use data returned from Microsoft Graph in single-page applications by using the OAuth 2.0 implicit grant flow.
  ms.date: 06/17/2021
  author: andrewconnell
  ms.author: v-johnco
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
title: Exercise - Single-page applications
durationInMinutes: 15
content: |
  [!include[](includes/3-exercise-single-page-applications.md)]
quiz:
  title: Test your knowledge
  questions:
  - content: "Which of the following options isn't a characteristic that makes SPAs stand out from web apps?"
    choices:
    - content: "Security characteristics of these apps are different from traditional server-based web applications"
      isCorrect: false
      explanation: "This is a recognized character difference between a SPA and a regular web app"
    - content: "JavaScript-based client-side solutions don't have the ability to process the authorization code used in other OAuth 2.0 flows"
      isCorrect: true
      explanation: "Correct! This isn't true."
    - content: "Full-page browser redirects away from the app become invasive to the user experience"
      isCorrect: false
      explanation: "This is a recognized character difference between a SPA and a regular web app"
    - content: "Many authorization servers and identity providers don't support CORS requests"
      isCorrect: false
      explanation: "This is a recognized character difference between a SPA and a regular web app"
  - content: "Why is an application secret not required when authenticating with Azure AD in a SPA?"
    choices:
    - content: "Instead of using an app secret, the SPA can use a x509 certificate. One of the two options is required."
      isCorrect: false
      explanation: "SPAs can't use a x509 certificate. The OAuth 2.0 implicit flow doesn't require a secret or certificate."
    - content: "They aren't needed because the user's password acts as the Azure AD app's secret."
      isCorrect: false
      explanation: "The user's password an Azure AD app's secret aren't compatible or used for each other."
    - content: "Secrets can't be reliably secured in a SPA because its inherently a client-side application. In no scenario can the secret reach the user's browser and be secured."
      isCorrect: true
      explanation: "Correct!"



