### YamlMime:ModuleUnit
uid: learn-m365.deploy-wvd.wvd-deployment-overview
title: Azure Virtual Desktop deployment overview
metadata:
  title: Azure Virtual Desktop deployment overview
  description: Learn about the terms used with Azure Virtual Desktop and options you can specify when you provision a host pool.
  ms.date: 12/15/2021
  author: lizap
  ms.author: nedelgad
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 5
content: |
  [!include[](includes/2-deployment-overview.md)]
