### YamlMime:ModuleUnit
uid: learn-m365.m365-teams-rooms-start-configure.review-configure-settings
title: Review and configure the Teams Rooms settings
metadata:
  title: Review and configure the Teams Rooms settings
  description: "**Start and configure Microsoft Teams Rooms** guides you through the configuration and testing steps to get Teams Rooms ready for production. Youâ€™ll learn about the out-of-box experience, key actions to take, and validation of the essential Teams Rooms features."
  ms.date: 07/15/2021
  author: AlexandraHrt
  ms.author: elizapo
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 10
content: |
  [!include[](includes/review-configure-settings.md)]