### YamlMime:ModuleUnit
uid: learn.wwl.manage-phone-system-for-microsoft-teams.configure-auto-attendants
title: Configure auto attendants
metadata:
  title: Configure auto attendants
  description: "Configure auto attendants"
  ms.date: 10/13/2021
  author: wwlpublish
  ms.author: jennyche
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/06-configure-auto-attendants.md)]