### YamlMime:ModuleUnit
uid: learn-m365-identity.m365-identity-overview.identity-core-security
title: Understand how identity is core to security
metadata:
  title: Understand how identity is core to security
  description:  Learn about identity and access management in Microsoft 365 and why identity is a core component of your organization’s security posture.
  ms.date: 07/07/2020
  author: AlexandraHrt 
  ms.author: v-aleha
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 3
content: |
  [!include[](includes/identity-core-security.md)]