### YamlMime:ModuleUnit
uid: learn-m365.msgraph-dotnet-core-show-user-emails.2-exercise-configure-azure-ad-app
metadata:
  title: Exercise - Configure an Azure AD app to connect to Microsoft 365
  description: In this unit, you'll create a new Azure Active Directory application registration that's necessary to complete exercises in this module.
  ms.date: 03/01/2022
  author: DanWahlin
  ms.author: dwahlin
  ms.topic: interactive-tutorial
  ms.prod: learning-graph
title: Exercise - Configure an Azure AD app to connect to Microsoft 365
durationInMinutes: 5
content: |
  [!include[](includes/2-exercise-configure-azure-ad-app.md)]
