### YamlMime:ModuleUnit
uid: learn.wwl.plan-your-identity-authentication-solution-for-microsoft-365.evaluate-multifactor-authentication-for-your-deployment
title: Evaluate multifactor authentication for your Microsoft 365 deployment
metadata:
  title: Evaluate multifactor authentication for your Microsoft 365 deployment
  description: "Evaluate multifactor authentication for your Microsoft 365 deployment"
  ms.date: 06/30/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 6
content: |
  [!include[](includes/3-evaluate-multifactor-authentication-for-your-deployment.md)]
quiz:
  title: "Check your knowledge"
  questions:
  - content: "You're the Enterprise Administrator for Tailspin Toys, Inc. Your companyâ€™s Microsoft 365 tenant is deployed in a Cloud Only environment. You're interested in enabling Azure Active Directory Multifactor authentication (MFA). Which of the following authentication options can Tailspin Toys use as a second type of authentication for MFA?"
    choices:
    - content: "Physical or virtual smart card"
      isCorrect: false
      explanation: "That's incorrect. This MFA option is only available in a hybrid setup that's managed on-premises. Try again."
    - content: "Text message"
      isCorrect: true
      explanation: "That's correct. In a Cloud Only deployment, Azure Active Directory MFA options include text message, phone call, and use of a mobile app."
    - content: "Azure MFA App"
      isCorrect: false
      explanation: "That's incorrect. This MFA option is only available in a hybrid setup that's managed on-premises. Try again."