### YamlMime:ModuleUnit
uid: learn.wwl.plan-your-identity-authentication-solution-for-microsoft-365.restrict-traffic-adfs-deployment
title: Restrict traffic in an ADFS deployment
metadata:
  title: Restrict traffic in an ADFS deployment
  description: "Restrict traffic in an ADFS deployment"
  ms.date: 06/30/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 5
content: |
  [!include[](includes/8-restrict-traffic-adfs-deployment.md)]