### YamlMime:ModuleUnit
uid: learn-m365.m365-compliance-information-protect-information.configure-sensitivity-label-policies
title: Configure sensitivity label policies
metadata:
  title: Configure sensitivity label policies
  description: Learn how to discover, classify, and protect sensitive and business-critical content throughout its lifecycle across your organization. 
  ms.date: 11/15/2021
  author: beccarobins
  ms.author: beccarobins
  ms.topic: interactive-tutorial
  ms.prod: learning-m365

durationInMinutes: 5
content: |
  [!include[](includes/configure-sensitivity-label-policies.md)]