### YamlMime:ModuleUnit
uid: learn-m365.wvd-security.2-enable-security
title: Enable security services for an Azure Virtual Desktop deployment
metadata:
  title: Enable security services for an Azure Virtual Desktop deployment
  description: After you complete this unit, you'll understand the Azure Virtual Desktop architecture and areas of responsibility for securing the deployment.
  ms.date: 07/13/2021
  author: ndelgado
  ms.author: nedelgad
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
durationInMinutes: 9
content: |
  [!include[](includes/2-enable-security.md)]
