### YamlMime:ModuleUnit
uid: learn.wwl.leverage-fasttrack-partner-services-to-support-microsoft-365.use-fasttrack-to-help-with-your-deployment
title: Use FastTrack to help with your Microsoft 365 deployment
metadata:
  title: Use FastTrack to help with your Microsoft 365 deployment
  description: "Use FastTrack to help with your Microsoft 365 deployment"
  ms.date: 06/30/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 5
content: |
  [!include[](includes/2-use-fasttrack-to-help-with-your-deployment.md)]
quiz:
  title: "Check your knowledge"
  questions:
  - content: "As the Enterprise Administrator for Fabrikam, you're planning the company's migration to Microsoft 365. To help you with this process, you're considering using Microsoft's FastTrack service. You know that with FastTrack, Microsoft will provide Fabrikam with personalized assistance. However, you're not sure how long the service will be available. How long is FastTrack available to a customer?"
    choices:
    - content: "FastTrack provides personalized assistance as long as the customer's subscription is active"
      isCorrect: true
      explanation: "That's correct. FastTrack provides organizations with personalized assistance at any time, as long as its subscription is active."
    - content: "FastTrack provides personalized assistance until the customer's Microsoft 365 tenant has been deployed"
      isCorrect: false
      explanation: "That's incorrect. This item isn't the correct amount of time that FastTrack is available to a customer. Try again."
    - content: "FastTrack provides personalized assistance for up to one year after the customer has purchased its Microsoft 365 subscription"
      isCorrect: false
      explanation: "That's incorrect. This item isn't the correct amount of time that FastTrack is available to a customer. Try again."