### YamlMime:ModuleUnit
uid: learn.wwl.leverage-fasttrack-partner-services-to-support-microsoft-365.request-partner-to-help-with-your-deployment
title: Request a partner to help with your Microsoft 365 deployment
metadata:
  title: Request a partner to help with your Microsoft 365 deployment
  description: "Request a partner to help with your Microsoft 365 deployment"
  ms.date: 06/30/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 1
content: |
  [!include[](includes/4-request-partner-to-help-with-your-deployment.md)]