### YamlMime:ModuleUnit
uid: learn.wwl.add-custom-domain-microsoft-365.plan-custom-domain-for-your-deployment
title: Plan a custom domain for your Microsoft 365 deployment
metadata:
  title: Plan a custom domain for your Microsoft 365 deployment
  description: "Plan a custom domain for your Microsoft 365 deployment"
  ms.date: 04/05/2022
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
labModal: false
durationInMinutes: 4
content: |
  [!include[](includes/2-plan-custom-domain-for-your-deployment.md)]