### YamlMime:ModuleUnit
uid: learn-m365.msgraph-show-user-emails.2-exercise-configure-azuread-app
metadata:
  title: Exercise - Configure an Azure AD app to connect to Microsoft 365
  description: In this unit, you'll create a new Azure Active Directory application registration that's necessary to complete exercises in this module.
  ms.date: 03/30/2021
  author: waldekmastykarz
  ms.author: wmastyka
  ms.topic: interactive-tutorial
  ms.prod: learning-graph
  ms.custom: team=cloud_advocates
  ms.contributors: wmastyka-04142021
title: Exercise - Configure an Azure AD app to connect to Microsoft 365
durationInMinutes: 3
content: |
  [!include[](includes/2-exercise-configure-azuread-app.md)]
