### YamlMime:ModuleUnit
uid: learn.wwl.implement-workplace-analytics.configure
title: Configure Workplace Analytics
metadata:
  title: Configure Workplace Analytics
  description: "Configure Workplace Analytics"
  ms.date: 07/01/2021
  author: wwlpublish
  ms.author: tfrink
  ms.topic: interactive-tutorial
  ms.prod: learning-m365
azureSandbox: false
durationInMinutes: 8
content: |
  [!include[](includes/5-configure.md)]